name: osm_api
description: Dart bindings for the OpenStreetMap API .
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  collection: ^1.15.0
  oauth1: ^2.0.0

dependencies:
  xml: ^6.1.0
  dio: ^4.0.0
  crypto: ^3.0.1