name: osm_api
description: Dart bindings for the OpenStreetMap API .
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
  oauth1: ^2.0.0

dependencies:
  xml: ^6.2.2
  dio: ^5.1.0
  crypto: ^3.0.2
  collection: ^1.17.1