name: osmapi
description: Dart bindings for the OpenStreetMap API .
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  collection: ^1.15.0
  oauth1: ^2.0.0

dependencies:
  xml: ^5.1.2
  dio: ^4.0.0